# Generated by Django 2.2.9 on 2020-02-24 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Inversiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('categoria', models.CharField(help_text='Categoria de Inversiones', max_length=50, unique=True, verbose_name='Categoria de Inversiones')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de Inversiones',
                'verbose_name_plural': 'Categoria de Inversiones',
            },
        ),
        migrations.CreateModel(
            name='TipoGiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripcion del Giro', max_length=100, verbose_name='Descripcion del Giro')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo del Giro',
                'verbose_name_plural': 'Tipo del Giro',
            },
        ),
        migrations.CreateModel(
            name='TipoContribuyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('tipo_contribuyente', models.CharField(help_text='Tipo de Contribuyente', max_length=50, verbose_name='Tipo de Contribuyente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Contribuyente',
                'verbose_name_plural': 'Tipo de Contribuyente',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Tipo de Documento', max_length=50, verbose_name='Tipo de Documento')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipo de Documento',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Pais', max_length=100, unique=True, verbose_name='Pais')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Ministerios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Ministerios', max_length=100, verbose_name='Ministerios')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
            },
        ),
        migrations.CreateModel(
            name='GiroCIIU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('codigo_giro', models.BigIntegerField(help_text='Codigo giro del CIIU', verbose_name='Codigo giro del CIIU')),
                ('descripcion', models.CharField(help_text='Descripcion del Giro', max_length=100, verbose_name='Descripcion del Giro')),
                ('tipo_giro', models.ForeignKey(help_text='Tipo Giro CIIU', on_delete=django.db.models.deletion.CASCADE, related_name='has_giro', to='Base.TipoGiro', verbose_name='Tipo Giro CIIU')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descripcion del Giro',
                'verbose_name_plural': 'Descripcion del Giro',
            },
        ),
        migrations.CreateModel(
            name='FechaBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('fecha_balance', models.CharField(choices=[('31/01', '31/01'), ('28/02', '28/02'), ('31/03', '31/03'), ('30/04', '30/04'), ('31/05', '31/05'), ('30/06', '30/06'), ('31/07', '31/07'), ('31/08', '31/08'), ('30/09', '30/09'), ('31/10', '31/10'), ('30/11', '30/11'), ('31/12', '31/12')], help_text='Fecha de Cierre de Balance', max_length=50, unique=True, verbose_name='Fecha Balance')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fecha de Balance',
                'verbose_name_plural': 'Fecha de Balance',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Departamento', max_length=100, verbose_name='Departamento')),
                ('pais', models.ForeignKey(help_text='Pais', on_delete=django.db.models.deletion.CASCADE, related_name='has_paises', to='Base.Pais', verbose_name='Pais')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamento',
                'unique_together': {('pais', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='SubCategoria_Inversiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('subcategoria', models.CharField(help_text='SubCategoria de Inversiones', max_length=50, verbose_name='SubCategoria de Inversiones')),
                ('categoria', models.ForeignKey(help_text='Categorias de Inversiones', on_delete=django.db.models.deletion.CASCADE, related_name='has_categorias', to='Base.Categoria_Inversiones', verbose_name='Categorias de Inversiones')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubCategoria de Inversiones',
                'verbose_name_plural': 'SubCategoria de Inversiones',
                'unique_together': {('categoria', 'subcategoria')},
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Localidad', max_length=100, verbose_name='Localidad')),
                ('departamento', models.ForeignKey(help_text='Departamento', on_delete=django.db.models.deletion.CASCADE, related_name='has_departamento', to='Base.Departamento', verbose_name='Departamento')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidad',
                'unique_together': {('departamento', 'descripcion')},
            },
        ),
    ]
